# Generated by Django 3.0.1 on 2022-06-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documnet',
            new_name='Document',
        ),
    ]
